# Generated by Django 4.0.1 on 2022-01-31 19:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_alter_game_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='game',
            name='trailer',
            field=models.CharField(blank=True, max_length=100, verbose_name='Трейлер'),
        ),
    ]
